### ISSUE TITLE
beugougnou

### ISSUE THREAD

**Issue by lmtlibass** [honorableCon/countries#1]
Amna wiki ba parei sokhlawougne ko 😂

**Comment by honorableCon** [comment]
Lolou lanla sax ?

**Comment by honorableCon** [comment]
Han ok lii dé sama yeuffou bopp la, ngani amna fane ?

**Comment by lmtlibass** [comment]
https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes

**Comment by honorableCon** [comment]
Je pouvais pas utiliser directement ça sur mon code.. 
comment tu fais pour utiliser la recherche Wikipedia pour créer un dropdown avec tous les pays avec les flags ? 🤔

**Comment by honorableCon** [comment]
@lmtlibass ??
